# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

resources:
  repositories:
  # The name used to reference this repository in the checkout step
  - repository: fib
    type: github
    endpoint: MSCICrawfordGitHub
    name: mscicrawford/fib
  - repository: winBatch
    type: github
    endpoint: MSCICrawfordGitHub
    name: mscicrawford/winBatch

stages:
- stage: InitialCheck
  variables:
    FIB_N: 8
  jobs:
  - job: windows
    pool:
      vmImage: 'windows-latest'
    steps:
    - checkout: winBatch
    - task: BatchScript@1
      displayName: "Find 3^4 using a windows batch script"
      inputs:
        filename: 'power.bat'
        arguments: '3 4'

  - job: ubuntu
    pool:
      name: 'default'
    steps:
    - checkout: fib

    - task: Bash@3
      displayName: "Find some stuff"
      inputs:
        filePath: 'fib.sh'

  - job: mac
    pool:
      vmImage: 'macOS-latest'
    steps:
    - checkout: fib

    - task: Bash@3
      displayName: "Find some stuff"
      inputs:
        filePath: 'fib.sh'

- stage: WindowsPROD
  dependsOn: InitialCheck
  condition: succeeded()
  jobs:
  - job: windows
    pool:
      vmImage: 'windows-latest'
    steps:
    - checkout: winBatch
    - task: BatchScript@1
      displayName: "Find 30^4 using a windows batch script"
      inputs:
        filename: 'power.bat'
        arguments: '30 4'

- stage: UbuntuProd
  dependsOn: InitialCheck
  condition: succeeded()
  variables:
    FIB_N: 800
  jobs:
  - job: ubuntu
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: fib

    - task: Bash@3
      displayName: "Find some stuff"
      inputs:
        filePath: 'fib.sh'

- stage: MacProd
  dependsOn: InitialCheck
  condition: succeeded()
  variables:
    FIB_N: 800
  jobs:
  - job: mac
    pool:
      vmImage: 'macOS-latest'
    steps:
    - checkout: fib

    - task: Bash@3
      displayName: "Find some stuff"
      inputs:
        filePath: 'fib.sh'

- stage: Final
  dependsOn:
  - WindowsPROD
  - UbuntuProd
  - MacProd
  condition: succeeded()
  jobs:
  - job: LogComplete
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: "echo 'Completed'"
