# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

resources:
  repositories:
  # The name used to reference this repository in the checkout step
  - repository: fib
    type: github
    endpoint: MSCICrawfordGitHub
    name: mscicrawford/fib
  - repository: winBatch
    type: github
    endpoint: MSCICrawfordGitHub
    name: mscicrawford/winBatch


- stage: CheckBothInParallel
  jobs:
  - job: windows
    pool:
      vmImage: 'windows-latest'
    steps:
    - checkout: winBatch

  - job: ubuntu
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: fib

